### ISSUE TITLE
Sending bower to background while composing an email

### ISSUE THREAD

**Issue by vivien** [wangp/bower#50] opened 2019-06-14 17:18 UTC
bower can be sent to background with e.g. ^Z and retrieved with `fg`. Same as for most editors. But this doesn't work anymore when using this editor from within bower when composing an email.

**Comment by wangp** [comment] 2019-06-15 02:13
It works for me. Going to need some more information I think.

**Comment by wangp** [comment] 2019-06-26 02:27
Actually, I can reproduce some kind of problem if I suspend an instance of vim that was called from bower. `fg` sometimes displays the bower compose screen, pressing ^L redraws the vim screen, and everything is confused.

**Comment by wangp** [comment] 2019-08-10 03:30
Should be fixed on master.

**Closed** 2019-08-10 03:30 UTC

**Comment by vivien** [comment] 2019-08-20 02:59
Sorry for taking a while to get back on this. It happens to be an issue from my editor Kakoune, not from bower... Good thing you found another issue though!

**Comment by seifferth** [comment] 2020-08-30 17:28
@vivien: Did you solve the issue? I am having the same problem with [vis](https://github.com/martanne/vis). Also: wrapping `vis` in other programs, such as `git commit` or shell scripts, doesn't cause this issue. I am not entirely sure, why `vis` behaves differently when called from bower, but being able to suspend it properly would still be nice.
